import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  camera: { flex: 1 },
  overlay: { flex: 1, justifyContent: 'flex-end', alignItems: 'center', paddingBottom: 50 },
  title: { color: '#fff', fontSize: 24, fontWeight: 'bold', marginBottom: 30 },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ff0000',
  },
  previewContainer: { flex: 1, backgroundColor: '#111' },
  scrollContent: { padding: 20, alignItems: 'center' },
  previewImage: { width: '100%', height: 400, borderRadius: 16, marginBottom: 20 },
  resultCard: { width: '100%', backgroundColor: '#222', borderRadius: 16, padding: 20, marginBottom: 20 },
  plantName: { fontSize: 22, fontWeight: 'bold', color: '#fff', textAlign: 'center' },
  scientificName: { fontSize: 13, fontStyle: 'italic', color: '#bbb', textAlign: 'center', marginTop: 2 },
  probability: { fontSize: 16, color: '#aaa', textAlign: 'center', marginBottom: 15 },
  edibleFlag: {
    backgroundColor: '#00c853',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 10,
  },
  edibleText: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  edibleParts: { color: '#fff', marginTop: 8, textAlign: 'center' },
  notEdibleFlag: {
    backgroundColor: '#d32f2f',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 10,
  },
  notEdibleText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  toxicity: { color: '#fff', marginTop: 5 },
  actions: { width: '100%', marginTop: 10 },
  button: {
    backgroundColor: '#1e88e5',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    marginVertical: 8,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  analyzeButton: { backgroundColor: '#00c853' },
  iconButton: {
    alignSelf: 'center',
    width: 56,
    height: 56,
    borderRadius: 28,
    paddingVertical: 0,
    paddingHorizontal: 0,
    justifyContent: 'center',
  },
  buttonText: { color: '#fff', fontSize: 18, fontWeight: '600' },
  disclaimer: {
    fontSize: 13,
    color: '#666',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 18,
  },
  message: { color: '#fff', fontSize: 18, textAlign: 'center', margin: 40 },
});
